/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import Business.EcoSystem;
import Business.SQLiteUtility.SQLiteUtility;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author hrishipal
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private EcoSystem ecosystem;
    private SQLiteUtility sqliteUtil = SQLiteUtility.getInstance();
    
    public MainJFrame() {
        initComponents();
        ecosystem = sqliteUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        loginArea = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();

        pfPassword = new javax.swing.JPasswordField();
        usernameJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UsernameIcon = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginArea.setBackground(new java.awt.Color(107, 33, 168));
        loginArea.setFocusable(false);
        loginArea.setMinimumSize(new java.awt.Dimension(294, 300));
        loginArea.setPreferredSize(new java.awt.Dimension(300, 768));
        loginArea.setRequestFocusEnabled(false);

        btnLogin.setBackground(new java.awt.Color(255, 0, 51));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        usernameJLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        usernameJLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameJLabel.setText("Username :");

        passwordJLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        passwordJLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordJLabel.setText("Password :");

        btnLogout.setBackground(new java.awt.Color(255, 0, 51));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setEnabled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACCOUNT LOGIN");

        UsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/secure.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Title.png"))); // NOI18N

        javax.swing.GroupLayout loginAreaLayout = new javax.swing.GroupLayout(loginArea);
        loginArea.setLayout(loginAreaLayout);
        loginAreaLayout.setHorizontalGroup(
            loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAreaLayout.createSequentialGroup()
                .addGroup(loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginAreaLayout.createSequentialGroup()
                        .addGroup(loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginAreaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(loginJLabel))
                            .addGroup(loginAreaLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginAreaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginAreaLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(passwordJLabel))
                                    .addGroup(loginAreaLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(usernameJLabel))
                                    .addComponent(passwordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(loginAreaLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(UsernameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(loginAreaLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(loginAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginAreaLayout.setVerticalGroup(
            loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAreaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(loginJLabel)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginAreaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(passwordJLabel))
                    .addGroup(loginAreaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(usernameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginAreaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(passwordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UsernameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginAreaLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(loginAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(btnLogin)))
        );

        jSplitPane1.setLeftComponent(loginArea);

        container.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FinalLogo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1070, 768));
        container.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 1324, 796);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
   String userName = txtUsername.getText().trim();
        String password = String.valueOf(pfPassword.getPassword()).trim();

        // 1) Try system‑level
        UserAccount userAccount = ecosystem.getUserAccountDirectory()
                                           .authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;

        // 2) Try enterprise & org‑level
        if (userAccount == null) {
            outer:
            for (Network network : ecosystem.getNetworks()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = enterprise.getUserAccountDirectory()
                                             .authenticateUser(userName, password);
                    if (userAccount != null) {
                        inEnterprise = enterprise;
                        break outer;
                    }
                    for (Organization org : 
                         enterprise.getOrganizationDirectory().getOrganizations()) {
                        if (org == null) continue;
                        userAccount = org.getUserAccountDirectory()
                                         .authenticateUser(userName, password);
                        if (userAccount != null) {
                            inEnterprise   = enterprise;
                            inOrganization = org;
                            break outer;
                        }
                    }
                }
            }
        }

        // 3) Invalid?
        if (userAccount == null) {
            txtUsername .setBorder(BorderFactory.createLineBorder(Color.RED));
            pfPassword  .setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(this, "Invalid credentials");
            return;
        }

        // 4) Valid – reset borders & show workArea
        txtUsername .setBorder(BorderFactory.createLineBorder(Color.GRAY));
        pfPassword  .setBorder(BorderFactory.createLineBorder(Color.GRAY));

        JPanel workArea = userAccount.getRole()
                                     .createWorkArea(
                                        container,
                                        userAccount,
                                        inOrganization,
                                        inEnterprise,
                                        ecosystem);

        container.add("workArea", workArea);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.show(container, "workArea");       // <— jump straight to this card

        // 5) Toggle buttons / fields
        btnLogin  .setEnabled(false);
        btnLogout .setEnabled(true);
        txtUsername.setEnabled(false);
        pfPassword .setEnabled(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

       // 1) Reset login controls
        btnLogout     .setEnabled(false);
        btnLogin      .setEnabled(true);
        txtUsername   .setEnabled(true);
        pfPassword    .setEnabled(true);
        txtUsername   .setBorder(BorderFactory.createLineBorder(Color.GRAY));
        pfPassword    .setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtUsername   .setText("");
        pfPassword    .setText("");

        // 2) Persist any changes
        sqliteUtil.storeSystem(ecosystem);

        // 3) Reset the right panel back to splash/login card only
        container.removeAll();
        container.add(jLabel1, "card2");            // re‑add your original image panel
        CardLayout layout = (CardLayout) container.getLayout();
        layout.show(container, "card2");

        container.revalidate();
        container.repaint();

        // 4) Bring focus (and caret) back to username
        txtUsername.requestFocusInWindow();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsernameIcon;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel loginArea;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JLabel passwordIcon;
    public javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField txtUsername;
    public javax.swing.JLabel usernameJLabel;
    // End of variables declaration//GEN-END:variables
}
