/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceOfficer;

import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceCompanyEnterprise;
import Business.Insurance.Insurance;
import Business.InsuredIndividual.InsuredIndividual;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;

import java.text.SimpleDateFormat;
import java.util.Calendar;

import java.util.List;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author chandrashekarreddykusukunthla
 */

public class AddNewPolicyHolderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewUserJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private InsuranceCompanyEnterprise insuranceCompanyEnterprise;
    private String policyNumber;

    public AddNewPolicyHolderJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, String policyNumber) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.insuranceCompanyEnterprise = (InsuranceCompanyEnterprise) enterprise;
        this.userAccount = userAccount;
        this.policyNumber = policyNumber;
        populateFields();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInsuranceMember = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        lblPersonalInformation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerPolicy = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        jDateChooserDob = new com.toedter.calendar.JDateChooser();
        lblFirstName = new javax.swing.JLabel();
        lblPolicyNumber = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtPolicyNumber = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox();
        lblLastName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lblPolicyCoverage = new javax.swing.JLabel();
        txtInsuranceCoverage = new javax.swing.JTextField();
        lblPolicyName = new javax.swing.JLabel();
        cmbInsurancePolicyName = new javax.swing.JComboBox();
        lblInsuranceInformation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(null);

        lblInsuranceMember.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblInsuranceMember.setText("ADD NEW INSURANCE MEMBER");
        add(lblInsuranceMember);
        lblInsuranceMember.setBounds(375, 16, 264, 21);

        btnAddCustomer.setBackground(new java.awt.Color(204, 204, 255));
        btnAddCustomer.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });
        add(btnAddCustomer);
        btnAddCustomer.setBounds(770, 510, 150, 30);

        lblPersonalInformation.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblPersonalInformation.setForeground(new java.awt.Color(0, 51, 51));
        lblPersonalInformation.setText("Customer Information");
        add(lblPersonalInformation);
        lblPersonalInformation.setBounds(10, 180, 180, 17);

        tblCustomerPolicy.setBackground(new java.awt.Color(204, 204, 255));
        tblCustomerPolicy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Policy Number", "Policy Name", "Coverage %", "SSN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerPolicy);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 560, 930, 109);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("All Customers");
        add(jLabel16);
        jLabel16.setBounds(54, 986, 83, 15);

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(6, 13, 90, 31);

        lblAddress.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(0, 51, 51));
        lblAddress.setText("Address :");

        lblSocialSecurityNumber.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblSocialSecurityNumber.setForeground(new java.awt.Color(0, 51, 51));
        lblSocialSecurityNumber.setText("SSN :");

        lblDOB.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(0, 51, 51));
        lblDOB.setText("Date of birth :");

        jDateChooserDob.setMaxSelectableDate(Calendar.getInstance().getTime());

        lblFirstName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 51, 51));
        lblFirstName.setText("First Name :");

        lblPolicyNumber.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblPolicyNumber.setForeground(new java.awt.Color(0, 51, 51));
        lblPolicyNumber.setText("Policy Number :");

        lblContact.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblContact.setForeground(new java.awt.Color(0, 51, 51));
        lblContact.setText("Phone :");

        lblGender.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 51, 51));
        lblGender.setText("Gender :");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male", "Other" }));

        lblLastName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 51, 51));
        lblLastName.setText("Last Name :");

        jDesktopPane1.setLayer(lblAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblSocialSecurityNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtSSN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblDOB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDateChooserDob, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblPolicyNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtFName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtPolicyNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblContact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtContact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblGender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cmbGender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(lblSocialSecurityNumber))
                .addGap(61, 61, 61)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContact)
                            .addComponent(lblGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(lblPolicyNumber)
                        .addGap(18, 18, 18)
                        .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB)
                            .addComponent(lblFirstName))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(lblLastName))
                            .addComponent(jDateChooserDob, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolicyNumber)
                    .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLastName)
                        .addComponent(txtFName)))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContact)
                                .addGap(81, 81, 81))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(lblSocialSecurityNumber))
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblAddress)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21))))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGender)
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        add(jDesktopPane1);
        jDesktopPane1.setBounds(10, 170, 620, 300);

        lblPolicyCoverage.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblPolicyCoverage.setForeground(new java.awt.Color(0, 51, 51));
        lblPolicyCoverage.setText("Insurance Coverage % :");

        lblPolicyName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblPolicyName.setForeground(new java.awt.Color(0, 51, 51));
        lblPolicyName.setText("Insurance Policy Name :");

        cmbInsurancePolicyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbInsurancePolicyNameFocusGained(evt);
            }
        });
        cmbInsurancePolicyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInsurancePolicyNameActionPerformed(evt);
            }
        });

        lblInsuranceInformation.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblInsuranceInformation.setForeground(new java.awt.Color(0, 51, 51));
        lblInsuranceInformation.setText("Insurance  Information");

        jDesktopPane2.setLayer(lblPolicyCoverage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtInsuranceCoverage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(lblPolicyName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(cmbInsurancePolicyName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(lblInsuranceInformation, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsuranceInformation)
                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane2Layout.createSequentialGroup()
                            .addComponent(lblPolicyCoverage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane2Layout.createSequentialGroup()
                            .addComponent(lblPolicyName)
                            .addGap(31, 31, 31)
                            .addComponent(cmbInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblInsuranceInformation)
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolicyName)
                    .addComponent(cmbInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyCoverage))
                .addGap(123, 123, 123))
        );

        add(jDesktopPane2);
        jDesktopPane2.setBounds(660, 170, 390, 300);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insurance_icon.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(860, 10, 150, 140);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed

        if (txtFName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter first name!");
            return;
        }

        if (txtName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter last name!");
            return;
        }

        if (jDateChooserDob.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please Enter Date of birth!");
            return;
        }

        if (cmbGender.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter Gender!");
            return;
        }

        if (cmbGender.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter Gender!");
            return;
        }

        if (txtSSN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter SSN!");
            return;
        }

        if (txtContact.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter phone!");
            return;
        }

        if (txtAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter address");
            return;
        }

        if (txtInsuranceCoverage.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide Insurance Coverage");
            return;
        } else {

            String firstName = txtFName.getText().trim();
            String lastName = txtName.getText().trim();
            SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
            String dateOfBirth = "";
            try {
                dateOfBirth = sdf.format(jDateChooserDob.getDate());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please select customer's dob");
            }
            String gender = cmbGender.getSelectedItem().toString();

            String ssn ;
            ssn = txtSSN.getText().trim();
            if (!ssnValidate()) {
                JOptionPane.showMessageDialog(null, "/* United States Social Security numbers are nine-digit numbers in the format AAA-GG-SSSS with following rules. */             \n"
                        + "              \"The first three digits called the area number. The area number cannot be 000, 666, or between 900 and 999\",\n"
                        + "                \" Digits four and five are called the group number and range from 01 to 99\",\n"
                        + "              \"The last four digits are serial numbers from 0001 to 9999.\"");
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.RED));

                return;
            }

            if (ssnValidate()) {
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            }

            String address = txtAddress.getText().trim();

            String phone = txtContact.getText().trim();

            if (!phonePatternCorrect()) {
                JOptionPane.showMessageDialog(null, "/* Following are valid phone number examples */             \n"
                        + "              \"1234567890\", \"123-456-7890\", \"(123)4567890\", \"(123)456-7890\",\n"
                        + "              /* Following are invalid phone numbers */ \n"
                        + "              \"(1234567890)\",\"123)4567890\", \"12345678901\", \"(1)234567890\",");
                txtContact.setBorder(BorderFactory.createLineBorder(Color.RED));

                return;
            }

            if (phonePatternCorrect()) {
                txtContact.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            }

            String policyNumber = txtPolicyNumber.getText().trim();
            String insurancePolicyName = cmbInsurancePolicyName.getSelectedItem().toString();

            double coverage = Double.parseDouble(txtInsuranceCoverage.getText().trim());

            try {
                Double.parseDouble(txtInsuranceCoverage.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide numerical values in coverage textfield!");
                return;
            }

            Insurance insurance = new Insurance(insurancePolicyName, insuranceCompanyEnterprise.getName(), coverage);

            InsuredIndividual insuranceIndividual = new InsuredIndividual(policyNumber, insurance);

            insuranceIndividual.setFirstName(firstName);
            insuranceIndividual.setLastName(lastName);
            insuranceIndividual.setDob(dateOfBirth);
            insuranceIndividual.setSex(gender);
            insuranceIndividual.setSocialSecurityID(ssn);
            insuranceIndividual.setContactNumber(phone);
            insuranceIndividual.setAddress(address);

            insuranceIndividual.setInsurance(insurance);

            insuranceCompanyEnterprise.getInsuranceCustomerList().getInsuranceHolders().add(insuranceIndividual);

            insuranceCompanyEnterprise.getInsuranceCustomerList().getInsuranceHolders();

            populateTable();
            refresh();
            JOptionPane.showMessageDialog(null, "Customer is created ! ");

        }

    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void cmbInsurancePolicyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbInsurancePolicyNameFocusGained
        System.out.println("Gained");
    }//GEN-LAST:event_cmbInsurancePolicyNameFocusGained

    private void cmbInsurancePolicyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInsurancePolicyNameActionPerformed

        Insurance selectedPolicy = (Insurance) cmbInsurancePolicyName.getSelectedItem();
        txtInsuranceCoverage.setText(String.valueOf(selectedPolicy.getCoveragepercentage()));
    }//GEN-LAST:event_cmbInsurancePolicyNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmbInsurancePolicyName;
    private com.toedter.calendar.JDateChooser jDateChooserDob;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblInsuranceInformation;
    private javax.swing.JLabel lblInsuranceMember;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPersonalInformation;
    private javax.swing.JLabel lblPolicyCoverage;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblPolicyNumber;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JTable tblCustomerPolicy;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtInsuranceCoverage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPolicyNumber;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables

    private boolean phonePatternCorrect() {

        Pattern pattern = Pattern.compile("\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}");
        Matcher matcher = pattern.matcher(txtContact.getText());

        boolean b = false;

        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }

        return b;
    }

    private boolean ssnValidate() {

        Pattern pattern = Pattern.compile("^(?!000|111)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000|1111)[0-9]{4}$");
        
        Matcher matcher = pattern.matcher(txtSSN.getText());

        boolean validate = false;

        if (matcher.matches()) {
            validate = true;
        } else {
            validate = false;
        }

        return validate;
    }

    private void refresh() {

        txtPolicyNumber.setText(UUID.randomUUID().toString().substring(0, 7));
        txtFName.setText("");
        txtName.setText("");
        txtContact.setText("");
        txtSSN.setText("");
        jDateChooserDob.setDate(null);
        txtAddress.setText("");

    }

    private void populateFields() {
        txtPolicyNumber.setText(policyNumber);
        List<Insurance> policies = insuranceCompanyEnterprise.getInsurancePolicyList().getInsurancePolicies();

        for (Insurance policy : policies) {
            cmbInsurancePolicyName.addItem(policy);
        }

        Insurance selectedPolicy = (Insurance) cmbInsurancePolicyName.getSelectedItem();
        
        if(selectedPolicy != null)
        {
        txtInsuranceCoverage.setText(String.valueOf(selectedPolicy.getCoveragepercentage()));
        }
        else{
            JOptionPane.showMessageDialog(null , "No Existing policy!");
            return;
        }

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblCustomerPolicy.getModel();

        dtm.setRowCount(0);
        List<InsuredIndividual> customers = insuranceCompanyEnterprise.getInsuranceCustomerList().getInsuranceHolders();
        for (InsuredIndividual customer : customers) {
            Object[] row = new Object[5];
            row[0] = customer.getFirstName() + " " + customer.getLastName();
            row[1] = customer;
            row[2] = customer.getInsurance().getPolicyName();
            row[3] = customer.getInsurance().getCoveragepercentage();
            row[4] = customer.getSocialSecurityID();

            dtm.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dtm);
        tblCustomerPolicy.setRowSorter(sorter);
    }
}
